### ISSUE TITLE
Version check code is unreachable

### ISSUE THREAD

**Issue by evildarkarchon** [sri-arjuna/SSE-CLA#2]
The condition for your python version check is missing a slice.
Current:
`if sys.version_info < (3, 3):` (which will always be false, reason stated below)
Should be:
`if sys.version_info[:2] < (3, 3):`
This is the output of print(sys.version_info) from my install:
`sys.version_info(major=3, minor=11, micro=2, releaselevel='final', serial=0)`
Without a slice, you would have to check for each one of those elements.

**Comment by sri-arjuna** [comment]
Fixed: https://github.com/sri-arjuna/SSE-CLA/commit/3687e23c394439d579220112d0e13ff4e2df5bce
